// Code generated by protoc-gen-gf-api. DO NOT EDIT.
// versions:
// - protoc-gen-gf-api v0.0.1
// - protoc            v3.19.4
// source: v1/article.proto

package v1

// This is a compile-time assertion to ensure that this generated file
// is compatible with the goframe package it is being compiled against.

import (
	"github.com/gogf/gf/v2/frame/g"
)

type GetArticlesReq struct {
	g.Meta `path:"/v1/articles" tags:"Blog" method:"GET"`

	Title string

	Page int32

	PageSize int32

	AuthorId int32
}

type GetArticlesRes struct {
	g.Meta `mime:"application/json"`

	Total int64

	Articles Article
}

type CreateArticleReq struct {
	g.Meta `path:"/v1/author/{author_id}/articles" tags:"Blog" method:"POST"`

	Title string

	Content string

	AuthorId int32
}

type CreateArticleRes struct {
	g.Meta `mime:"application/json"`

	Title string

	Content string

	AuthorId int32
}
