// Code generated by protoc-gen-gf-client. DO NOT EDIT.
// versions:
// - protoc-gen-gf-client v0.0.1
// - protoc               v3.19.4
// source: v1/article.proto

package v1

// This is a compile-time assertion to ensure that this generated file
// is compatible with the goframe package it is being compiled against.

import (
	"context"
	"fmt"

	"github.com/gogf/gf/v2/errors/gcode"
	"github.com/gogf/gf/v2/errors/gerror"
	"github.com/gogf/gf/v2/frame/g"
)

type sBlogClient struct{}

func New() *sBlogClient {
	return &sBlogClient{}
}

func init() {
	service.RegisterBlogClient(New())
}

func (s *sBlogClient) GetArticles(ctx context.Context, in *GetArticlesInput) (out *GetArticlesOutput, err error) {
	server, _ := g.Cfg().Get(ctx, "serverUri.blogServer")
	if _, err := g.Client().GET(
		ctx,
		fmt.Sprintf("%s/v1/articles", server),
		g.Map{
			"id": in.Id,
		},
	); err != nil {
		g.Log().Errorf(ctx, "sBlogClient GetArticles Client error %v", err)
		return nil, gerror.NewCode(gcode.CodeInternalError, common_consts.MessageSystemBusy)
	}

	return &model.GetArticlesOutput{}, nil
}

type GetArticlesInput struct {
	Title string

	Page int32

	PageSize int32

	AuthorId int32
}

type GetArticlesOutput struct {
	Total int64

	Articles Article
}
