// Code generated by protoc-gen-gf-api.
// versions:
// - protoc-gen-gf-api v0.0.1
// - protoc            v4.24.2
// source: v1/test.proto

package test

// This is a compile-time assertion to ensure that this generated file
// is compatible with the goframe package it is being compiled against.

type ListUser1Req struct {
	g.Meta   `path:"/user1" method:"GET"`
	Page     int    `json:"page"`
	PageSize int    `json:"page_size"`
	Keyword  string `json:"keyword"`
}

type ListUser1Res struct {
	g.Meta `mime:"application/json"`
	Total  int `json:"total"`
	List   any `json:"list"`
}

type GetUser1Req struct {
	g.Meta `path:"/user1" method:"GET"`
	Id     string `json:"id"`
}

type GetUser1Res struct {
	g.Meta    `mime:"application/json"`
	CreatedAt string
	Id        int32
	Password  string
	Username  string
}

type CreateUser1Req struct {
	g.Meta   `path:"/user1" method:"PATCH"`
	Password string
	Username string
}

type CreateUser1Res struct {
	g.Meta `mime:"application/json"`
}

type UpdateUser1Req struct {
	g.Meta   `path:"/user1" method:"PUT"`
	Id       int32
	Password string
	Username string
}

type UpdateUser1Res struct {
	g.Meta `mime:"application/json"`
}

type DeleteUser1Req struct {
	g.Meta `path:"/user1" method:"DELETE"`
	Id     string `json:"id"`
}

type DeleteUser1Res struct {
	g.Meta `mime:"application/json"`
}

type ListUser1Copy1Req struct {
	g.Meta   `path:"/user1-copy1" method:"GET"`
	Page     int    `json:"page"`
	PageSize int    `json:"page_size"`
	Keyword  string `json:"keyword"`
}

type ListUser1Copy1Res struct {
	g.Meta `mime:"application/json"`
	Total  int `json:"total"`
	List   any `json:"list"`
}

type GetUser1Copy1Req struct {
	g.Meta `path:"/user1-copy1" method:"GET"`
	Id     string `json:"id"`
}

type GetUser1Copy1Res struct {
	g.Meta    `mime:"application/json"`
	CreatedAt string
	Id        int32
	Password  string
	Username  string
}

type CreateUser1Copy1Req struct {
	g.Meta   `path:"/user1-copy1" method:"PATCH"`
	Password string
	Username string
}

type CreateUser1Copy1Res struct {
	g.Meta `mime:"application/json"`
}

type UpdateUser1Copy1Req struct {
	g.Meta   `path:"/user1-copy1" method:"PUT"`
	Id       int32
	Password string
	Username string
}

type UpdateUser1Copy1Res struct {
	g.Meta `mime:"application/json"`
}

type DeleteUser1Copy1Req struct {
	g.Meta `path:"/user1-copy1" method:"DELETE"`
	Id     string `json:"id"`
}

type DeleteUser1Copy1Res struct {
	g.Meta `mime:"application/json"`
}
